version: '3.9'
services:
  db:
    restart: always
    image: ermogenes/top5-mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - data:/var/lib/mysql
  web:
    restart: always
    build: .
    ports:
      - 8080:80
    environment:
      ConnectionStrings__top5Connection: server=db;port=3306;user=root;password=secret;database=top5
volumes:
  data: